spring:
  data:
    mongodb:
      uri: mongodb+srv://sbdesis:Desibandhu%402024%21@sangamwebappfree.clugh.mongodb.net/?retryWrites=true&w=majority&appName=SangamWebApp
      database: SangamWebDB

  freemarker:
    template-loader-path: classpath:/templates
    suffix: .ftl
    charset: UTF-8
    prefer-file-system-access: false
